import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { Header } from "./layouts/header";
import { Footer } from "./layouts/footer";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} h-auto bg-no-repeat bg-fixed bg-[#030115] `}>
        <video autoPlay loop muted playsInline className="absolute w-full opacity-60">
          <source src="images/background.mp4" />
        </video>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
