const routes = {
  home: "/",
  addLiquidity: "/liquidity",
  swap: "https://swap.espento.network/swap#/",
  bridge: "https://app.espento.network/bridge",
  farm: "/farm",
  farmV3: "/farm/v3",
  farmV4: "/farm/v4",
  info: "/info",
  blog: "/blog",
  stake: "/stake",
  stakeV3: "/stake/v3",
  stakeV4: "/stake/v4",
  borrow: "/borrow",
  affiliate: "/affiliate",
  profile: "/profile",
  roadmap: "/roadmap",
  policy: "/policy",
  career: "/career",
  terms: "/terms",
  migration: "/migration",
  brandAssets: "/brandAssets",
  disclaimer: "/disclaimer",
  support: "/support",
  contest: "/contest",
  dao: "/dao",
  game: "/game",
  dev: "/dev",
  tokenomics: "/tokenomics",
  docs: {
    home: "/docs",
  },
};

export default routes;
